### PR TITLE
add Carthage support

### PR DESCRIPTION
**Pull request by AndrewSB**

### CODE REVIEW

**Comment by oseparovic** [comment]
Carthage only supports frameworks on iOS 8 and later. This lib (at least attempts to be) compatible down to iOS 6. I would also like to avoid adding all that xcode meta data junk if possible.

Thanks for the suggestion

**Comment by AndrewSB** [comment]
I know there are alot of people (myself included) who are targeting iOS 8+ and use Carthage for dependency management, can this be pushed to a `carthage` branch (I'll create a new Pull Request)?

**Comment by AndrewSB** [comment]
@oseparovic: bump. I wanted to delete my fork

**Comment by oseparovic** [comment]
I added the xcode files. Keep in mind I am no longer actively maintaining the library. If you notice any bugs, please send me another pull request

**Comment by AndrewSB** [comment]
Thanks @oseparovic! Will do 😄

**Pull request merged**
